begin;

create table if not exists aegisops_control.lifecycle_transition_records (
  transition_id text primary key,
  subject_record_family text not null,
  subject_record_id text not null,
  previous_lifecycle_state text,
  lifecycle_state text not null,
  transitioned_at timestamptz not null,
  attribution jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  check (
    subject_record_family in (
      'alert',
      'analytic_signal',
      'case',
      'evidence',
      'observation',
      'lead',
      'recommendation',
      'approval_decision',
      'action_request',
      'action_execution',
      'hunt',
      'hunt_run',
      'ai_trace',
      'reconciliation'
    )
  ),
  check (
    lifecycle_state in (
      'new',
      'triaged',
      'investigating',
      'escalated_to_case',
      'closed',
      'reopened',
      'superseded',
      'active',
      'withdrawn',
      'open',
      'pending_action',
      'contained_pending_validation',
      'collected',
      'validated',
      'linked',
      'captured',
      'confirmed',
      'challenged',
      'promoted_to_alert',
      'promoted_to_case',
      'proposed',
      'under_review',
      'accepted',
      'rejected',
      'materialized',
      'pending',
      'approved',
      'expired',
      'canceled',
      'draft',
      'pending_approval',
      'executing',
      'completed',
      'failed',
      'unresolved',
      'dispatching',
      'queued',
      'running',
      'succeeded',
      'on_hold',
      'concluded',
      'planned',
      'generated',
      'accepted_for_reference',
      'rejected_for_reference',
      'matched',
      'mismatched',
      'stale',
      'resolved'
    )
  ),
  check (
    previous_lifecycle_state is null or previous_lifecycle_state in (
      'new',
      'triaged',
      'investigating',
      'escalated_to_case',
      'closed',
      'reopened',
      'superseded',
      'active',
      'withdrawn',
      'open',
      'pending_action',
      'contained_pending_validation',
      'collected',
      'validated',
      'linked',
      'captured',
      'confirmed',
      'challenged',
      'promoted_to_alert',
      'promoted_to_case',
      'proposed',
      'under_review',
      'accepted',
      'rejected',
      'materialized',
      'pending',
      'approved',
      'expired',
      'canceled',
      'draft',
      'pending_approval',
      'executing',
      'completed',
      'failed',
      'unresolved',
      'dispatching',
      'queued',
      'running',
      'succeeded',
      'on_hold',
      'concluded',
      'planned',
      'generated',
      'accepted_for_reference',
      'rejected_for_reference',
      'matched',
      'mismatched',
      'stale',
      'resolved'
    )
  )
);

commit;
