#!/usr/bin/env bash

set -euo pipefail
umask 077

LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lab-common.sh
source "${LAB_DIR}/lab-common.sh"

[[ "$#" -eq 0 ]] || fail "usage: $0"
load_lab_environment
assert_safe_runtime_root "${AEGISOPS_LAB_RUNTIME_ROOT}"
require_command openssl

secret_dir="${AEGISOPS_LAB_RUNTIME_ROOT}/secrets"
cert_dir="${AEGISOPS_LAB_RUNTIME_ROOT}/proxy-certs"
evidence_dir="${AEGISOPS_LAB_RUNTIME_ROOT}/evidence"
wazuh_source_dir="${AEGISOPS_LAB_RUNTIME_ROOT}/substrates/wazuh-docker"
wazuh_config_dir="${wazuh_source_dir}/single-node/config"
shuffle_app_dir="${AEGISOPS_LAB_RUNTIME_ROOT}/shuffle/apps"
shuffle_file_dir="${AEGISOPS_LAB_RUNTIME_ROOT}/shuffle/files"

mkdir -p \
  "${secret_dir}" \
  "${cert_dir}" \
  "${evidence_dir}" \
  "${shuffle_app_dir}" \
  "${shuffle_file_dir}"

write_secret_once() {
  local path="$1"
  local bytes="${2:-32}"

  if [[ ! -s "${path}" ]]; then
    openssl rand -hex "${bytes}" >"${path}"
  fi
  chmod 600 "${path}"
}

write_strong_secret_once() {
  local path="$1"
  local existing=""

  if [[ -s "${path}" ]]; then
    existing="$(<"${path}")"
  fi
  if [[ -z "${existing}" || "${existing}" =~ ^[0-9a-f]{48}$ ]]; then
    printf 'Aa1!%sZz9!\n' "$(openssl rand -hex 24)" >"${path}"
  fi
  chmod 600 "${path}"
}

write_secret_once "${secret_dir}/postgres-password" 24
write_secret_once "${secret_dir}/wazuh-ingest-shared-secret"
write_secret_once "${secret_dir}/wazuh-ingest-proxy-secret"
write_secret_once "${secret_dir}/protected-surface-proxy-secret"
write_secret_once "${secret_dir}/admin-bootstrap-token"
write_secret_once "${secret_dir}/break-glass-token"
write_secret_once "${secret_dir}/wazuh-indexer-password" 24
write_secret_once "${secret_dir}/wazuh-api-password" 24
write_strong_secret_once "${secret_dir}/shuffle-opensearch-password"
write_secret_once "${secret_dir}/shuffle-encryption-modifier"

postgres_password="$(<"${secret_dir}/postgres-password")"
printf 'postgresql://aegisops_control_plane:%s@postgres:5432/aegisops_control_plane\n' \
  "${postgres_password}" >"${secret_dir}/control-plane-postgres-dsn"
chmod 600 "${secret_dir}/control-plane-postgres-dsn"

if [[ -e "${cert_dir}/lab.key" || -e "${cert_dir}/lab.crt" ]]; then
  [[ -s "${cert_dir}/lab.key" && -s "${cert_dir}/lab.crt" ]] \
    || fail "proxy TLS state is partial; restore or remove both lab.key and lab.crt before rerunning init"
else
  openssl req -x509 -newkey rsa:3072 -sha256 -nodes \
    -keyout "${cert_dir}/lab.key" \
    -out "${cert_dir}/lab.crt" \
    -days 30 \
    -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" >/dev/null 2>&1
fi
chmod 600 "${cert_dir}/lab.key" "${cert_dir}/lab.crt"

cat >"${RUNTIME_ENV}" <<EOF
# Generated by Phase 67.1 init.sh. Keep this file untracked.
AEGISOPS_LAB_COLIMA_PROFILE=${AEGISOPS_LAB_COLIMA_PROFILE}
AEGISOPS_LAB_DOCKER_CONTEXT=${AEGISOPS_LAB_DOCKER_CONTEXT}
AEGISOPS_LAB_COMPOSE_PROJECT_NAME=${AEGISOPS_LAB_COMPOSE_PROJECT_NAME}
AEGISOPS_LAB_RUNTIME_ROOT=${AEGISOPS_LAB_RUNTIME_ROOT}
AEGISOPS_LAB_SECRET_DIR=${secret_dir}
AEGISOPS_LAB_PROXY_CERT_DIR=${cert_dir}
AEGISOPS_LAB_EVIDENCE_DIR=${evidence_dir}
AEGISOPS_LAB_WAZUH_SOURCE_DIR=${wazuh_source_dir}
AEGISOPS_LAB_WAZUH_CONFIG_DIR=${wazuh_config_dir}
AEGISOPS_LAB_SHUFFLE_APP_DIR=${shuffle_app_dir}
AEGISOPS_LAB_SHUFFLE_FILE_DIR=${shuffle_file_dir}
AEGISOPS_LAB_NETWORK_SUBNET=${AEGISOPS_LAB_NETWORK_SUBNET}
AEGISOPS_LAB_PROXY_IPV4=${AEGISOPS_LAB_PROXY_IPV4}
AEGISOPS_LAB_CONTROL_PLANE_IPV4=${AEGISOPS_LAB_CONTROL_PLANE_IPV4}
AEGISOPS_LAB_POSTGRES_IPV4=${AEGISOPS_LAB_POSTGRES_IPV4}
AEGISOPS_LAB_WAZUH_MANAGER_IPV4=${AEGISOPS_LAB_WAZUH_MANAGER_IPV4}
AEGISOPS_LAB_WAZUH_INDEXER_IPV4=${AEGISOPS_LAB_WAZUH_INDEXER_IPV4}
AEGISOPS_LAB_WAZUH_DASHBOARD_IPV4=${AEGISOPS_LAB_WAZUH_DASHBOARD_IPV4}
AEGISOPS_LAB_SHUFFLE_BACKEND_IPV4=${AEGISOPS_LAB_SHUFFLE_BACKEND_IPV4}
AEGISOPS_LAB_SHUFFLE_OPENSEARCH_IPV4=${AEGISOPS_LAB_SHUFFLE_OPENSEARCH_IPV4}
AEGISOPS_LAB_SHUFFLE_FRONTEND_IPV4=${AEGISOPS_LAB_SHUFFLE_FRONTEND_IPV4}
AEGISOPS_LAB_PROXY_PORT=${AEGISOPS_LAB_PROXY_PORT}
AEGISOPS_LAB_WAZUH_DASHBOARD_PORT=${AEGISOPS_LAB_WAZUH_DASHBOARD_PORT}
AEGISOPS_LAB_SHUFFLE_FRONTEND_PORT=${AEGISOPS_LAB_SHUFFLE_FRONTEND_PORT}
AEGISOPS_LAB_MIN_CPUS=${AEGISOPS_LAB_MIN_CPUS}
AEGISOPS_LAB_MIN_MEMORY_GIB=${AEGISOPS_LAB_MIN_MEMORY_GIB}
AEGISOPS_LAB_MIN_DISK_GIB=${AEGISOPS_LAB_MIN_DISK_GIB}
AEGISOPS_LAB_WAZUH_PLATFORM=${AEGISOPS_LAB_WAZUH_PLATFORM}
AEGISOPS_LAB_SHUFFLE_PLATFORM=${AEGISOPS_LAB_SHUFFLE_PLATFORM}
AEGISOPS_LAB_ALLOW_EMULATION=${AEGISOPS_LAB_ALLOW_EMULATION}
AEGISOPS_LAB_WAZUH_VERSION=${AEGISOPS_LAB_WAZUH_VERSION}
AEGISOPS_LAB_WAZUH_DOCKER_COMMIT=${AEGISOPS_LAB_WAZUH_DOCKER_COMMIT}
AEGISOPS_LAB_SHUFFLE_VERSION=${AEGISOPS_LAB_SHUFFLE_VERSION}
AEGISOPS_LAB_WAZUH_INDEXER_PASSWORD=$(<"${secret_dir}/wazuh-indexer-password")
AEGISOPS_LAB_WAZUH_API_PASSWORD=$(<"${secret_dir}/wazuh-api-password")
AEGISOPS_LAB_SHUFFLE_OPENSEARCH_PASSWORD=$(<"${secret_dir}/shuffle-opensearch-password")
AEGISOPS_LAB_SHUFFLE_ENCRYPTION_MODIFIER=$(<"${secret_dir}/shuffle-encryption-modifier")
EOF
chmod 600 "${RUNTIME_ENV}"

echo "Initialized Phase 67.1 runtime at ${AEGISOPS_LAB_RUNTIME_ROOT}"
echo "Next: ${LAB_DIR}/preflight.sh --write-evidence"
